import { describe, expect, it } from 'vitest'
import source from './ProjectQorTrendPanel.vue?raw'

describe('ProjectQorTrendPanel', () => {
  it('renders the embedded QoR overview score chart and delta card', () => {
    expect(source).toContain('QoR Overview')
    expect(source).not.toContain('QoR Trend')
    expect(source).toContain('Overall Score')
    expect(source).toContain("label: 'Regressions'")
    expect(source).toContain('Baseline:')
    expect(source).toContain('baselineLabel')
    expect(source).toContain('baselineWorkspaceId')
    expect(source).toContain('ri-download-line')
    expect(source).toContain("'export-report'")
    expect(source).toContain('ri-flag-line')
    expect(source).toContain("'set-baseline'")
    expect(source).toContain('requestSetSelectedWorkspaceAsBaseline')
    expect(source).toContain('scoreTicks')
    expect(source).toContain('qor-chart-gridline')
    expect(source).toContain('threshold')
    expect(source).toContain('qor-chart-axis')
    expect(source).toContain('qor-chart-y-axis')
    expect(source).toContain('qor-chart-x-axis')
    expect(source).toContain('qor-chart-point')
    expect(source).toContain('highestTrendScore')
    expect(source).toContain('qor-chart-workspace-label')
    expect(source).toContain('qor-best-score-chip')
    expect(source).toContain('qor-chart-legend')
    expect(source).toContain('role="tablist"')
    expect(source).toContain('activeDeltaTab')
    expect(source).not.toContain('Missing Analysis')
    expect(source).not.toContain('Selected Workspace')
    expect(source).not.toContain('unsupportedModules')
    expect(source).not.toContain('qor-trend-points')
  })

  it('keeps the plot boundary and point hierarchy visually distinct', () => {
    expect(source).toContain('qor-chart-plot-bg')
    expect(source).toContain('qor-lollipop')
    expect(source).toContain('qor-chart-stem')
    expect(source).toContain('qor-chart-value-label')
    expect(source).toContain('stroke-dasharray: 2.8 2.2')
    expect(source).toContain('font-size: 3.5px')
    expect(source).toContain('font-size: 3.1px')
    expect(source).toContain('.qor-chart-point.best')
    expect(source).toContain('.qor-chart-score-label.threshold')
    expect(source).not.toContain('qor-score-area')
    expect(source).not.toContain('qor-score-polyline')
    expect(source).not.toContain('pass 60')
    expect(source).not.toContain('qor-chart-threshold-caption')
    expect(source).not.toContain('qor-chart-best-ring')
  })

  it('marks non-eligible workspaces as NR without a fabricated score point or line segment', () => {
    expect(source).toContain('isNotRated: point.score === null')
    expect(source).toContain('const chartNotRatedY = 56')
    expect(source).not.toContain('scorePolylines')
    expect(source).not.toContain('scoreAreaPaths')
    expect(source).toContain('v-if="!point.isNotRated"')
    expect(source).toContain('qor-chart-not-rated')
    expect(source).toContain('qor-chart-nr-pill')
    expect(source).toContain('Not rated')
    expect(source).not.toContain('score === null ? 50')
  })

  it('uses prepared QoR model data instead of reading project files directly', () => {
    expect(source).toContain('qorTrendSummary')
    expect(source).not.toContain('readOptionalProjectTextFile')
    expect(source).not.toContain('feature/')
    expect(source).not.toContain('output/')
  })

  it('keeps export and baseline actions without making trend points selectable', () => {
    expect(source).toContain('defineEmits')
    expect(source).toContain('exportReport')
    expect(source).toContain('requestSetSelectedWorkspaceAsBaseline')
    expect(source).toContain('confirmBaselineChange')
    expect(source).not.toContain("'select-point'")
    expect(source).not.toContain('selectTrendPoint')
  })

  it('stacks the chart and findings vertically with dashboard scrolling', () => {
    expect(source).not.toContain('.slice(0, 4)')
    expect(source).toContain('qor-scroll-list')
    expect(source).toContain('qor-chart-viewport')
    expect(source).toContain('ref="chartViewport"')
    expect(source).toContain('.qor-chart-viewport {')
    expect(source).toContain('min-height: 280px;')
    expect(source).toContain('height: 280px;')
    expect(source).toContain('overflow: hidden;')
    expect(source).toContain('width: 100%;')
    expect(source).toContain('height: 100%;')
    expect(source).toContain('const chartLeft = 20')
    expect(source).toContain('const chartRight = 8')
    expect(source).toContain('const chartBottom = 68')
    expect(source).toContain('grid-template-columns: minmax(0, 1fr);')
    expect(source).toContain('grid-template-rows: auto auto;')
    expect(source).toContain('overflow: visible;')
    expect(source).not.toContain('minmax(300px, 0.44fr)')
  })

  it('uses workspace names and shortens axis labels beyond eight characters', () => {
    expect(source).toContain('shortenWorkspaceLabel(point.label)')
    expect(source).toContain('const maxLength = 8')
    expect(source).toContain('`${label.slice(0, maxLength)}...`')
    expect(source).toContain('<title>{{ point.label }}</title>')
  })

  it('renders slanted workspace labels under the x-axis ticks', () => {
    expect(source).toContain('qor-chart-workspace-tick')
    expect(source).toContain('qor-chart-x-tick')
    expect(source).toContain('transform="rotate(-40)"')
    expect(source).toContain('text-anchor="end"')
    expect(source).not.toContain('workspaceLabelAnchor')
    expect(source).not.toContain('chartWorkspaceLabelY')
  })

  it('anchors the full-width score chart at the bottom-left plot origin', () => {
    expect(source).toContain('new ResizeObserver')
    expect(source).toContain('chartCoordinateWidth')
    expect(source).toContain('chartViewportSize')
    expect(source).toContain('? chartLeft')
    expect(source).not.toContain('chartLeft + plotWidth / 2')
  })

  it('renders regressions and improvements as a delta comparison table', () => {
    expect(source).toContain('qor-delta-table')
    expect(source).toContain('isDeltaCompareTab')
    expect(source).toContain('activeDeltaCompareItems')
    expect(source).toContain('formatMetricValue')
    expect(source).toContain('formatAbsoluteDelta')
    expect(source).toContain('deltaBarWidth')
    expect(source).toContain('deltaBaselineColumnLabel')
    expect(source).toContain('deltaCurrentColumnLabel')
    expect(source).toContain('activeRiskItems')
    expect(source).not.toContain('qor-delta-priority')
    expect(source).not.toContain('regressionPriorityLabel')
  })

  it('uses workspace names instead of internal IDs in QoR delta details', () => {
    expect(source).toContain('baselineLabel')
    expect(source).toContain('triage.baselineWorkspaceName')
    expect(source).toContain('deltaBaselineColumnLabel')
    expect(source).not.toContain("'message' in delta ? delta.message : delta.workspaceId")
  })

  it('surfaces structured analysis risks in a dedicated scrollable tab', () => {
    expect(source).toContain("label: 'Risks'")
    expect(source).toContain("activeDeltaTab.value === 'risks'")
    expect(source).toContain('props.qorTrendSummary.risks')
    expect(source).toContain('activeRiskItems')
    expect(source).toContain('selectedWorkspaceRiskCount')
    expect(source).toContain('qor-risk-table')
    expect(source).toContain('qor-severity-pill')
    expect(source).toContain('activeRiskEmptyMessage')
    expect(source).toContain('Select a workspace to review structured risks.')
    expect(source).toContain('qor-risk-critical')
    expect(source).toContain('qor-risk-warning')
  })

  it('uses visible QoR finding tabs and keeps timing investigation actionable', () => {
    expect(source).toContain("label: 'Timing'")
    expect(source).toContain("label: 'Risks'")
    expect(source).toContain("label: 'Regressions'")
    expect(source).toContain("label: 'Improvements'")
    expect(source).toContain('class="qor-delta-tabs"')
    expect(source).toContain('class="qor-delta-tab"')
    expect(source).toContain('handleDeltaTabKeydown')
    expect(source).toContain('tabCount(tab.id)')
    expect(source).not.toContain('qor-delta-edge-rail')
    expect(source).not.toContain('qor-vertical-tab')
    expect(source).not.toContain('writing-mode: vertical-rl')
    expect(source).toContain("'select-workspace'")
    expect(source).toContain('selectTimingIssueWorkspace(issue.workspaceId)')
    expect(source).toContain('timingClosure.issues')
    expect(source).toContain('timingClosure.coverage')
    expect(source).toContain('timingClosure.triage')
    expect(source).toContain('visibleTimingIssues')
    expect(source).toContain('filteredVisibleTimingIssues')
    expect(source).toContain('filteredClearedTimingTriage')
    expect(source).toContain('filteredTimingCoverage')
    expect(source).toContain('filteredTimingWorkItemCount')
    expect(source).toContain('projectTimingWorkItemCount')
    expect(source).toContain('selectedTimingSummary')
    expect(source).toContain('qor-timing-table')
    expect(source).toContain('toggleTimingIssueExpand')
    expect(source).toContain('hasTimingForWorkspace')
    expect(source).toContain('.qor-delta-table.is-regressions tbody td:last-child,')
    expect(source).not.toContain('.qor-delta-table tbody td:last-child {\n  width: 72px;')
    expect(source).toContain('currentTriageIssueKeys')
    expect(source).toContain('clearedTimingTriage')
    expect(source).toContain('formatMissingCornerCount(coverage.missingCornerCount)')
    expect(source).toContain(
      'formatAvailableArtifactCount(coverage.availableArtifactCount)',
    )
    expect(source).toContain('formatTimingClockDelays(issue)')
    expect(source).toContain('formatTimingTriage(issue)')
    expect(source).toContain('formatTimingPhysicalContext(issue)')
    expect(source).toContain('Observed physical changes:')
    expect(source).toContain('formatTimingReviewHints(issue)')
    expect(source).toContain('Review next:')
    expect(source).toContain('timingTriageLabel(issue)')
    expect(source).toContain('RESOLVED vs')
    expect(source).toContain('Launch ${launch.toFixed(3)} ns')
    expect(source).toContain('Capture ${capture.toFixed(3)} ns')
  })

  it('keeps baseline and export actions in a compact toolbar', () => {
    expect(source).toContain('qor-panel-toolbar')
    expect(source).toContain('qor-toolbar-button')
    expect(source).not.toContain('qor-overview-header')
    expect(source).not.toContain('qor-baseline-button')
    expect(source).not.toContain('qor-export-button')
    expect(source).toContain('baselineChangePending')
    expect(source).toContain('Confirm baseline')
    expect(source).not.toContain('qor-summary-grid')
  })

  it('exposes comparison context, score context near the chart, and selected-workspace deltas', () => {
    expect(source).toContain('qor-selection-context')
    expect(source).toContain('v-if="selectedWorkspaceIsBaseline"')
    expect(source).toContain('Viewing baseline')
    expect(source).toContain('Comparing')
    expect(source).toContain('with baseline')
    expect(source).toContain('selectedWorkspaceIsBaseline')
    expect(source).toContain('item.workspaceId === workspaceId')
    expect(source).not.toContain('qor-baseline-hint')
    expect(source).not.toContain('Changes the project QoR reference.')
    expect(source).toContain('selectedScoreContext')
    expect(source).toContain('qor-score-context')
    expect(source).toContain('qor-attention')
    expect(source).toContain('Needs attention')
    expect(source).toContain('class="qor-attention-rank"')
    expect(source).toContain("index === 0 ? 'Priority' : 'Next'")
    expect(source).toContain('attentionThresholdContext')
    expect(source).toContain('riskAttentionDetail(workspaceId)')
    expect(source).not.toContain('selectAttentionItem')
    expect(source).not.toContain('qor-attention-action')
    expect(source).not.toContain('ri-arrow-right-line')
    expect(source).toContain('60 is an analysis threshold, not signoff.')
    expect(source).toContain('Signoff separate')
    expect(source).toContain('activeDeltaTab.value = initialDeltaTab()')
    expect(source).toContain('qor-chart-data')
    expect(source).toContain('<summary>Score data</summary>')
    expect(source).not.toContain('<th scope="col">Context</th>')
    expect(source).toContain('chartAccessibleSummary')
    expect(source).toContain('aria-describedby="qor-chart-description"')
    expect(source).toContain('60 analysis threshold')
    expect(source).toContain(':tabindex="activeDeltaTab === tab.id ? 0 : -1"')
    expect(source).toContain('class="qor-timing-select"')
  })
})
